takeoff:

  during_takeoff:
    controller: "MpcController"
    tracker: "LandoffTracker"

  after_takeoff:
    controller: "So3Controller"
    tracker: "MpcTracker"

  takeoff_height: 2.5

landing:

  disarm: true
