supersoft:

  horizontal:
    kp: 2.3
    kv: 1.5
    ka: 1.0

    attitude:
      kq: 5.0

    kib: 0.1
    kib_lim: 10.0

    kiw: 0.1
    kiw_lim: 10.0

  vertical:
    kp: 5.0
    kv: 5.0
    ka: 1.0

    attitude:
      kq: 5.0

  mass_estimator:
    km: 0.5
    km_lim: 6.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

soft:

  horizontal:
    kp: 2.5
    kv: 1.8
    ka: 1.0

    attitude:
      kq: 7.0

    kib: 0.1
    kib_lim: 10.0

    kiw: 0.1
    kiw_lim: 10.0

  vertical:
    kp: 15.0
    kv: 10.0
    ka: 1.0

    attitude:
      kq: 5.0

  mass_estimator:
    km: 0.5
    km_lim: 6.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

tight:

  horizontal:
    kp: 2.8
    kv: 2.0
    ka: 1.0

    attitude:
      kq: 7.0

    kib: 0.1
    kib_lim: 10.0

    kiw: 0.1
    kiw_lim: 10.0

  vertical:
    kp: 15.0
    kv: 10.0
    ka: 1.0

    attitude:
      kq: 5.0

  mass_estimator:
    km: 0.5
    km_lim: 6.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

supertight:

  horizontal:
    kp: 3.1
    kv: 2.0
    ka: 1.0

    attitude:
      kq: 7.0

    kib: 0.1
    kib_lim: 10.0

    kiw: 0.1
    kiw_lim: 10.0

  vertical:
    kp: 15.0
    kv: 10.0
    ka: 1.0

    attitude:
      kq: 5.0

  mass_estimator:
    km: 0.5
    km_lim: 6.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
