# periodically checks if max height was exceeded
# if so, retakes control and descends below it
max_height_checking:

  enabled: false

# periodically checks if min height was exceeded
# if so, retakes control and ascends above it
min_height_checking:

  enabled: false
  min_height: 3.0 # [m]

takeoff:

  during_takeoff:
    controller: "MpcController"
    tracker: "LandoffTracker"

  after_takeoff:
    controller: "Se3Controller"
    tracker: "MpcTracker"

  takeoff_height: 2.5

landing:

  landing_tracker: "LandoffTracker"
  landing_controller: "MpcController"

midair_activation:

  after_activation:
    controller: "Se3Controller"
    tracker: "MpcTracker"
