gains: [
  "supersoft",
  "soft",
  "tight"
]


gain_management:

  # list of allowed gains per odometry mode
  allowed_gains:
    hector: ["supersoft"]
    aloam: ["supersoft"]
    vio: ["supersoft"]
    rtk: ["supersoft", "soft", "tight"]
    gps_garmin: ["supersoft", "soft", "tight"]
    gps_baro: ["supersoft", "soft", "tight"]
    optflow: ["supersoft"]
    other: ["supersoft"]

  # those gains will be used automatically when a localization mode switches
  # and the current gains are not in the allowed list (next paragraphs)
  fallback_gains:
    hector: "supersoft"
    aloam: "supersoft"
    vio: "supersoft"
    rtk: "soft"
    gps_garmin: "soft"
    gps_baro: "soft"
    optflow: "supersoft"
    other: "supersoft"
