Se3Controller:
  address: "mrs_uav_controllers/Se3Controller"
  namespace: "se3_controller"
  eland_threshold: 0.0 # [m], position error triggering eland
  failsafe_threshold: 0.0 # [m], position error triggering failsafe land
  odometry_innovation_threshold: 0.0 # [m], position odometry innovation threshold

MpcController:
  address: "mrs_uav_controllers/MpcController"
  namespace: "mpc_controller"
  eland_threshold: 0.0 # [m], position error triggering eland
  failsafe_threshold: 0.0 # [m], position error triggering failsafe land
  odometry_innovation_threshold: 0.0 # [m], position odometry innovation threshold
