mrs_uav_managers:

  gain_manager:

    supersoft:

      horizontal:
        kp: 2.3
        kv: 1.5
        ka: 1.0

        kib: 0.1
        kib_lim: 10.0

        kiw: 0.1
        kiw_lim: 10.0

      vertical:
        kp: 8.0
        kv: 5.0
        ka: 1.0

      attitude:
        kq_roll_pitch: 5.0
        kq_yaw: 5.0

      mass_estimator:
        km: 1.0

        # the maximum estimated uav mass difference
        km_lim: 10.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
