gains: [
  "default",
]

gain_management:

  # list of allowed gains per odometry mode
  allowed_gains:
    hector: ["default"]
    aloam: ["default"]
    vio: ["default"]
    rtk: ["default"]
    gps: ["default"]
    optflow: ["default"]
    other: ["default"]

  # those gains will be used automatically when a localization mode switches
  # and the current gains are not in the allowed list (next paragraphs)
  fallback_gains:
    hector: "default"
    aloam: "default"
    vio: "default"
    rtk: "default"
    gps: "default"
    optflow: "default"
    other: "default"
