gains: [
  "supersoft",
  "soft",
]

gain_management:

  # list of allowed gains per odometry mode
  allowed_gains:
    hector_garmin: ["soft"]
    aloam: ["soft"]
    vio: ["supersoft"]
    rtk: ["supersoft"]
    gps_garmin: ["supersoft", "soft"]
    gps_baro: ["supersoft", "soft"]
    optflow: ["supersoft"]
    other: ["supersoft"]

  # those gains will be used automatically when a localization mode switches
  # and the current gains are not in the allowed list (next paragraphs)
  fallback_gains:
    hector_garmin: "soft"
    aloam: "soft"
    vio: "supersoft"
    rtk: "supersoft"
    gps_garmin: "supersoft"
    gps_baro: "supersoft"
    optflow: "supersoft"
    other: "supersoft"
