rate: 25

estimator_types: [
  "OBJECT",
  "VIO",
  "ICP",
  "RTK",
  "OPTFLOWGPS",
  "GPS",
  "GPS_GYRO",
  "GPS_COMPASS",
  "OPTFLOW",
  "OTHER",
]

constraints: [
  "slow",
  "medium",
  "fast",
]

constraint_management:

  # list of allowed gains per odometry mode
  allowed_constraints:
    OBJECT: ["slow"]
    VIO: ["slow"]
    ICP: ["slow"]
    RTK: ["slow"]
    OPTFLOWGPS: ["slow"]
    GPS: ["slow", "medium", "fast"]
    GPS_GYRO: ["slow", "medium", "fast"]
    GPS_COMPASS: ["slow", "medium", "fast"]
    OPTFLOW: ["slow"]
    OTHER: ["slow"]

  # those gains will be used automatically when a localization mode switches
  # and the current gains are not in the allowed list (next paragraphs)
  fallback_constraints:
    OBJECT: "slow"
    VIO: "slow"
    ICP: "slow"
    RTK: "slow"
    OPTFLOWGPS: "slow"
    GPS: "slow"
    GPS_GYRO: "slow"
    GPS_COMPASS: "slow"
    OPTFLOW: "slow"
    OTHER: "slow"
