## --------------------------------------------------------------
## |                 Detailed model description                 #
## --------------------------------------------------------------

# these model parameters can be used when
# - 'attitude rate', and/or
# - 'actuator control'
# are done by the MRS system.

model_params:

  arm_length: 0.27 # [m]
  body_height: 0.1 # [m]

  propulsion:

    # force [N] = force_constant * rpm^2
    force_constant: 0.00000012216

    # torque [Nm] = torque_constant * force [N]
    torque_constant: 0.07

    prop_radius: 0.11 # [m]

    # allocation motors -> torques

    # quadrotor X configuration
    # hexarotor X configuration
    # [roll torque,      [            [RPM_1^2,
    #  pitch torque,  =    Alloc    *  RPM_2^2,
    #  yaw torque,         Matrix       ...
    #  thrust force]              ]    RPM_n_motors^2]
    allocation_matrix: [
      1, -1, -0.5,  0.5,  0.5,   -0.5, # *= force_constant*arm_length
      0, 0,  -0.87, 0.87, -0.87, 0.87, # *= force_constant*arm_length
      1, -1, 1,     -1,   -1,    1,    # *= torque_constant*force_constant
      1, 1,  1,     1,    1,     1     # *= force_constant
    ]

    rpm:
      min: 906   # [revolutions/minute]
      max: 9068  # [revolutions/minute]
