rate: 25

estimator_types: [
  "T265",
  "OBJECT",
  "VIO",
  "ICP",
  "RTK",
  "OPTFLOWGPS",
  "GPS",
  "OPTFLOW",
  "OTHER",
]

constraints: [
  "darpa",
]

constraint_management:

  # list of allowed gains per odometry mode
  allowed_constraints:
    T265: ["darpa"]
    OBJECT: ["darpa"]
    VIO: ["darpa"]
    ICP: ["darpa"]
    RTK: ["darpa"]
    OPTFLOWGPS: ["darpa"]
    GPS: ["darpa"]
    OPTFLOW: ["darpa"]
    OTHER: ["darpa"]

  # those gains will be used automatically when a localization mode switches
  # and the current gains are not in the allowed list (next paragraphs)
  fallback_constraints:
    T265: "darpa"
    OBJECT: "darpa"
    VIO: "darpa"
    ICP: "darpa"
    RTK: "darpa"
    OPTFLOWGPS: "darpa"
    GPS: "darpa"
    OPTFLOW: "darpa"
    OTHER: "darpa"
