darpa:

  horizontal:
    speed: 0.5
    acceleration: 0.5
    jerk: 3.0
    snap: 3.0

  vertical:

    ascending:
      speed: 1.0
      acceleration: 1.0
      jerk: 3.0
      snap: 3.0

    descending:
      speed: 1.0
      acceleration: 1.0
      jerk: 3.0
      snap: 3.0

  yaw:
    speed: 0.5
    acceleration: 0.5
    jerk: 3.0
    snap: 5.0
