# - list of names of dynamically loaded trackers
# - trackers follow the mrs_uav_manager/Tracker.h interface
trackers : [
  "mrs_trackers/LandoffTracker",
  "mrs_trackers/LineTracker",
  "mrs_trackers/MpcTracker",
  "mrs_trackers/JoyTracker",
]

# - list of names of dynamically loaded controllers
# - controllers follow the mrs_uav_manager/Controller.h interface
controllers : [
  "mrs_controllers/So3Controller",
  "mrs_controllers/NsfController",
  "mrs_controllers/FailsafeController",
  "mrs_controllers/AttitudeController",
]

# - this is the "do nothing tracker", which is active when no other is
# - NullTracker is defined in the mrs_uav_manager package
null_tracker: "mrs_uav_manager/NullTracker"

status_timer_rate:  10 # [Hz]

safety:

  safety_timer_rate: 100 # [Hz]
  failsafe_timer_rate: 100 # [Hz]

  tilt_limit_eland: 60 # [deg]
  tilt_limit_disarm: 90 # [deg]

  control_error_eland: 1.0 # [m]
  control_error_failsafe: 2.0 # [m]

  # - this tracker will be used for calling the emergancy hover routine
  ehover_tracker: "mrs_trackers/LandoffTracker"

  # - this controller will be used for emergancy landing
  failsafe_controller: "mrs_controllers/FailsafeController"
  odometry_max_missing_time: 0.1 # [s]

  elanding_timer_rate: 10
  elanding_cutoff_height:  1.0
  elanding_cutoff_mass_factor:  0.5 # how much lighter does the drone appear to be?

joystick:
  joystick_timer_rate: 30 # [Hz]
