null_tracker: "mrs_uav_manager/NullTracker"

max_height_checking:

  rate: 10 # [Hz]
  safety_height_offset: 0.5 # how much lower to descend bellow the max height

takeoff:
  rate: 10 # [Hz]
  takeoff_tracker: "mrs_trackers/LandoffTracker"
  after_takeoff_tracker: "mrs_trackers/MpcTracker"

  takeoff_height: 2.0

  ground_limit_height: 0.5 # under which height the takeoff can happen

landing:

  rate: 10 # [Hz]
  landing_tracker: "mrs_trackers/LandoffTracker"

  # those two must apply simultaneously
  landing_cutoff_height:  0.5
  landing_cutoff_mass_factor:  0.3 # how much light does the drone appear to be?
