rate: 25

estimator_types: [
  "T265",
  "OBJECT",
  "VIO",
  "ICP",
  "RTK",
  "OPTFLOWGPS",
  "GPS",
  "OPTFLOW",
  "OTHER",
]

gains: [
  "optflow",
  "optflow_dark",
]

gain_management:

  # list of allowed gains per odometry mode
  allowed_gains:
    T265: ["optflow"]
    OBJECT: ["optflow"]
    VIO: ["optflow"]
    ICP: ["optflow"]
    RTK: ["optflow"]
    OPTFLOWGPS: ["optflow"]
    GPS: ["optflow"]
    OPTFLOW: ["optflow", "optflow_dark"]
    OTHER: ["optflow"]

  # those gains will be used automatically when a localization mode switches
  # and the current gains are not in the allowed list (next paragraphs)
  fallback_gains:
    T265: "optflow"
    OBJECT: "optflow"
    VIO: "optflow"
    ICP: "optflow"
    RTK: "optflow"
    OPTFLOWGPS: "optflow"
    GPS: "optflow"
    OPTFLOW: "optflow"
    OTHER: "optflow"
