fast:

  horizontal:
    speed: 8.0
    acceleration: 2.5
    jerk: 10.0
    snap: 20.0

  vertical:

    ascending:
      speed: 2.0
      acceleration: 2.0
      jerk: 5.0
      snap: 3.0

    descending:
      speed: 2.0
      acceleration: 2.0
      jerk: 5.0
      snap: 3.0

  heading:
    speed: 1.0
    acceleration: 2.0
    jerk: 10.0
    snap: 10.0
