gains: [
  "supersoft",
  "soft",
]


gain_management:

  # list of allowed gains per odometry mode
  allowed_gains:
    hector_garmin: ["supersoft"]
    aloam: ["supersoft"]
    vio: ["supersoft"]
    rtk: ["supersoft", "soft"]
    gps: ["supersoft", "soft"]
    optflow: ["supersoft", "soft"]
    other: ["supersoft"]

  # those gains will be used automatically when a localization mode switches
  # and the current gains are not in the allowed list (next paragraphs)
  fallback_gains:
    aloam: "supersoft"
    vio: "supersoft"
    rtk: "supersoft"
    gps: "supersoft"
    optflow: "supersoft"
    other: "supersoft"
