null_tracker: "mrs_mav_manager/NullTracker"

landoff:
  takeoff_tracker: "mrs_trackers/LandoffTracker"
  landing_tracker: "mrs_trackers/LandoffTracker"
  landing_cutoff_height:  0.30
  landing_cutoff_speed:  0.05
