null_tracker: "mrs_mav_manager/NullTracker"

takeoff:
  rate: 10 # [Hz]
  takeoff_tracker: "mrs_trackers/LandoffTracker"
  after_takeoff_tracker: "mrs_trackers/MpcTracker"

  takeoff_height: 1.5

landing:

  rate: 10 # [Hz]
  landing_tracker: "mrs_trackers/LandoffTracker"

  # those two must apply simultaneously
  landing_cutoff_height:  0.4
  landing_cutoff_mass_difference:  0.5 # [kg]
