default:

  horizontal:
    kp: 4.0
    kv: 3.0
    ka: 1.0

    attitude:
      kq: 6.0
      kw: 0.0

    kib: 0.5
    kib_lim: 10.0

    kiw: 0.5
    kiw_lim: 10.0

  vertical:
    kp: 10.0
    kv: 5.0
    ka: 1.0

    attitude:
      kq: 6.0
      kw: 0.0

  weight_estimator:
    km: 1.0
    km_lim: 8.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
