supersoft:

  horizontal:
    kp: 6.4
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 5.0
      kw: 0.0

    kib: 0.2
    kib_lim: 10.0

    kiw: 0.2
    kiw_lim: 10.0

  vertical:
    kp: 10.0
    kv: 10.0
    ka: 1.0

    attitude:
      kq: 5.0
      kw: 2.0

  weight_estimator:
    km: 1.0
    km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

soft:

  horizontal:
    kp: 6.4
    kv: 4.0
    ka: 1.0

    attitude:
      kq: 5.0
      kw: 0.0

    kib: 0.2
    kib_lim: 10.0

    kiw: 0.2
    kiw_lim: 10.0

  vertical:
    kp: 30.0
    kv: 16.0
    ka: 1.0

    attitude:
      kq: 10.4
      kw: 2.0

  weight_estimator:
    km: 1.0
    km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
