supersoft:

  horizontal:
    kp: 0.20
    kv: 0.08
    ka: 1.0

    kib: 0.01
    kib_lim: 0.15

    kiw: 0.01
    kiw_lim: 0.3

  vertical:
    kp: 0.6
    kv: 0.2
    ka: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

soft:

  horizontal:
    kp: 10.0
    kv: 5.0
    ka: 1.0

    kib: 0.01
    kib_lim: 0.15

    kiw: 0.01
    kiw_lim: 0.3

  vertical:
    kp: 0.6
    kv: 0.2
    ka: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

tight:

  horizontal:
    kp: 20.0
    kv: 10.0
    ka: 1.0

    kib: 0.01
    kib_lim: 0.15

    kiw: 0.01
    kiw_lim: 0.3

  vertical:
    kp: 0.6
    kv: 0.2
    ka: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
