fast:

  horizontal:
    speed: 8.0
    acceleration: 3.0
    jerk: 10.0
    snap: 20.0

  vertical:

    ascending:
      speed: 4.0
      acceleration: 3.0
      jerk: 10.0
      snap: 20.0

    descending:
      speed: 4.0
      acceleration: 3.0
      jerk: 10.0
      snap: 20.0

  heading:
    speed: 1.0
    acceleration: 2.0
    jerk: 10.0
    snap: 10.0
