supersoft:

  horizontal:
    kp: 5.0
    kv: 3.0
    ka: 1.0

    attitude:
      kq: 6.0
      kw: 0.0

    kib: 1.0
    kib_lim: 10.0

    kiw: 1.0
    kiw_lim: 10.0

  vertical:
    kp: 10.0
    kv: 10.0
    ka: 1.0

    attitude:
      kq: 2.0
      kw: 2.0

  weight_estimator:
    km: 1.0
    km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]
