supersoft:

  horizontal:
    kp: 0.15
    kv: 0.20
    ka: 1.0

    kib: 0.01
    kib_lim: 0.15

    kiw: 0.01
    kiw_lim: 0.3

  vertical:
    kp: 0.6
    kv: 0.2
    ka: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 1.0

soft:

  horizontal:
    kp: 0.40
    kv: 0.25
    ka: 1.0

    kib: 0.01
    kib_lim: 0.15

    kiw: 0.01
    kiw_lim: 0.3

  vertical:
    kp: 0.6
    kv: 0.2
    ka: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 1.0 # [kg]

tight:

  horizontal:
    kp: 0.50
    kv: 0.40
    ka: 1.0

    kib: 0.01
    kib_lim: 0.15

    kiw: 0.01
    kiw_lim: 0.3

  vertical:
    kp: 0.6
    kv: 0.2
    ka: 1.0

  weight_estimator:
    km: 1.0
    km_lim: 1.0 # [kg]
