supersoft:

  horizontal:
    kp: 4.0
    kv: 2.5
    ka: 1.0

    attitude:
      kq: 6.0
      kw: 0.0

    kib: 1.0
    kib_lim: 1.0

    kiw: 1.5
    kiw_lim: 5.0

  vertical:
    kp: 150.0
    kv: 70.0
    ka: 1.0

    attitude:
      kq: 20.0
      kw: 5.0

  weight_estimator:
    km: 1.0
    km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

soft:

  horizontal:
    kp: 10.0
    kv: 5.0
    ka: 1.0

    attitude:
      kq: 6.0
      kw: 0.0

    kib: 1.0
    kib_lim: 1.0

    kiw: 1.5
    kiw_lim: 5.0

  vertical:
    kp: 150.0
    kv: 70.0
    ka: 1.0

    attitude:
      kq: 20.0
      kw: 5.0

  weight_estimator:
    km: 1.0
    km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection]

tight:

  horizontal:
    kp: 20.0
    kv: 10.0
    ka: 1.0

    attitude:
      kq: 6.0
      kw: 0.0

    kib: 1.0
    kib_lim: 1.0

    kiw: 1.5
    kiw_lim: 5.0

  vertical:
    kp: 150.0
    kv: 70.0
    ka: 1.0

    attitude:
      kq: 20.0
      kw: 5.0

  weight_estimator:
    km: 1.0
    km_lim: 3.0 # [kg, at least 1/2 of the UAVs mass to allow landing detection] 
